### ISSUE TITLE
A better readme needed

### ISSUE THREAD

**Issue by darshjain** [keshavsingh4522/Python#129]
Readme file needs to give a better description and a few optimizations needed.

**Comment by darshjain** [comment]
Please assign this to me

**Comment by keshavsingh4522** [comment]
ok @darshjain , i assigne you this task if completed then make pull request

**Comment by darshjain** [comment]
If you like my work please follow me, check my repositories out and please you are welcome to make pull requests in them. 
Dont forget the star the ones you like :)
Thanks!!!
